version: "3.8"

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped

  postgres_client:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PG_ADMIN_PORT}
    ports:
      - ${PG_ADMIN_PORT}:${PG_ADMIN_PORT}
    depends_on:
      - postgres

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    depends_on:
      - postgres

  server:
    build: "."
    container_name: server
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${SERVER_DB}
      #KEYCLOAK_USER: ${KEYCLOAK_USER}
      #KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      KEYCLOAK_REALM_CERT_URL: ${KEYCLOAK_REALM_CERT_URL}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - keycloak
      - postgres
    