server:
  port: ${SERVER_PORT:8000}
spring:
  application.name: ClayMarket
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8080/auth/realms/master/protocol/openid-connect/certs}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/claymarket}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:post123post}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update
logging.level.org.hibernate:
  SQL: DEBUG
  BasicBinder: TRACE