server:
  port: ${SERVER_PORT:8000}
spring:
  application.name: ClayMarket
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8080/auth/realms/master/protocol/openid-connect/certs}
