server:
  port: ${SERVER_PORT:8000}
spring:
  application.name: ClayMarket
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8080/auth/realms/master/protocol/openid-connect/certs}
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:claymarket}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:post123post}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: update